---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/atlantis version
      register: atlantis_test_output
    - debug:
        msg: '{{ atlantis_test_output.stdout }}'
